### ISSUE TITLE
is this support multi session?

### ISSUE THREAD

**Issue by akmaldira** [AliAryanTech/Chisato-WhatsApp#3]

**Comment by AliAryanTech** [comment]
Indeed

**Comment by akmaldira** [comment]
but here on the Server.ts
`if (!session || !this.client || this.client.config.session !== (req.query.session as string))`

this.client.config.session just for 1 session

**Comment by akmaldira** [comment]
i mean multi session, so this can handle 2 numbers of bot with same condition

**Comment by akmaldira** [comment]
> > but here on the Server.ts `if (!session || !this.client || this.client.config.session !== (req.query.session as string))`
> > this.client.config.session just for 1 session
> 
> Session is made for one, but it's multi device

ah i know, just make new Client in bot.ts

**Comment by AliAryanTech** [comment]
> i mean multi session, so this can handle 2 numbers of bot with same condition

Ooh, I see you need to write them in one, also separate session by env

**Comment by akmaldira** [comment]
> > i mean multi session, so this can handle 2 numbers of bot with same condition
> 
> Ooh, I see you need to write them in one, also separate session by env

thanks, i see it

**Comment by AliAryanTech** [comment]
> > > i mean multi session, so this can handle 2 numbers of bot with same condition
> > 
> > 
> > Ooh, I see you need to write them in one, also separate session by env
> 
> thanks, i see it

Ppl don't rarely make issues so I don't add anything
