### ISSUE TITLE
how can i deploy it on heroku

### ISSUE THREAD

**Issue by Guru322** [AliAryanTech/Chisato-WhatsApp#6]
Configuring build environment
-----> Building runtime environment
-----> TypeScript app detected
-----> Could not find tsc executable. Build aborted
 !     Push rejected, failed to compile TypeScript app.
 !     Push failed

it's the build log

**Comment by AliAryanTech** [comment]
Heroku no longer free, you need a paid account to use heroku, here is guide for deployment with heroku - [here](https://github.com/AliAryanTech/Chisato-WhatsApp/blob/master/Heroku-Hosting-Guide.md)

**Comment by Guru322** [comment]
Bro i have a paid heroku account where i can deploy

as that guide says 
i can't find the heroku deploy buttun

**Comment by AliAryanTech** [comment]
Fork repo and use your fork repo in heroku app

**Comment by Guru322** [comment]
which build pack to use ?
i used https://github.com/zidizei/heroku-buildpack-tsc
this earlier

**Comment by Guru322** [comment]
i sucessfully deployed it but it's saying command can only be used in groups 
but it's not responsing in groups

**Comment by AliAryanTech** [comment]
> Bro i have a paid heroku account where i can deploy
> 
> as that guide says i can't find the heroku deploy buttun

Alright fine, 
[![Deploy with Heroku](https://www.herokucdn.com/deploy/button.svg "Deploy with `Heroku")](https://heroku.com/deploy?template=https://github.com/AliAryanTech/Chisato-WhatsApp/blob/master/` "Deploy with Heroku")

**Comment by AliAryanTech** [comment]
> i sucessfully deployed it but it's saying command can only be used in groups but it's not responsing in groups

It's fine, restart it once
